name: Tests

on:
  push:
    branches:
      - main
  pull_request: {}

jobs:
  unit_test:
    runs-on: ubuntu-latest

    steps:
      - name: Cancel Outdated Runs
        uses: styfle/cancel-workflow-action@0.7.0
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip3-${{ hashFiles('*requirements.txt') }}
      - name: Install dependencies
        run: pip install -e .[dev]
      - name: Check package version conflicts
        run: pip check
      - name: Run unit tests
        run: pytest -vv tests/unit_tests -n auto
  integration_test:
    runs-on: ubuntu-latest
    steps:
      - name: Launch test server
        run: cd tests/integration_tests && docker-compose up -d
      - name: Run integration tests
        run: pytest . -vv
